### PR TITLE
Fix Cerberus Max Engine Value (#1)

### PR DESCRIPTION
**Pull request by Ariphaos**
The book lists the Engine max as 4.

### CODE REVIEW

**Comment by drewg13** [comment]
I'm aware, but the sheets give it only 3 boxes. It seems more likely to me that a single number in the book is a typo than that they left an entire block of boxes off of the sheet.  The official errata I was able to find didn't address the discrepancy, so I went with 3. Thanks for submitting as a PR though.

**Comment by Ariphaos** [comment]
So you are making this your call, rather than the GMs?

**Comment by drewg13** [comment]
Whether you intended it so or not, that came across as fairly hostile.  Ultimately, your proposed PR only substitutes your preferred resolution for mine, doing nothing to resolve the issue for any other hypothetical undecided GMs, so that seems like an unproductive criteria by which to judge any proposed resolution.  Frankly, I have no problem *at all* using my own judgment to make calls on ambiguous default values that are end-user editable in a system that I created and continue to support at no charge.  As a point in your favor, this particular value is not *easily* end-user editable.  It strikes me as mildly arrogant to drop a PR without at least attempting to determine if there was a reason for the discrepancy, but I make allowances for the internet being a medium that sometimes seems to actively discourage nuance and politeness, so I assumed it was well-intentioned and thought an explanation of my reasoning would be sufficient.

But, to address your underlying concern, there are a number of methods for making adjustments to this value that don't involve going to the trouble of submitting a PR, any of which I would have been happy to help any hypothetical GM make, if asked.  Hell, I do my best to help provide support and macros for Blades, which isn't even my system.

The simplest method would just be tweaking the value manually in your local system files, although this has the downside of being lost on the next system update and involves editing DB files, which is very much not recommended, so that's not a good choice for anything but the most immediate need.

A slightly more involved method would be to create a Cerberus-type ship Actor and use a macro to tweak the value after creation.  I've helped people come up with macros to do this type of thing in the past, so it wouldn't be difficult.  This would be persistent on the Actor, but would need to be repeated any time the Ship Type item was added to an existing or new Actor.  Not a bad option, but not ideal.

A better method would be to import the Cerberus Ship Type Item into your world and modify it there, which the system would then use preferentially over the compendium version included with the system, so long as it has an identical name.  As there's no built-in UI available to modify this particular value (which you presumably noticed), the best way to do this would be to use the Export Data option on the imported item to save it as a JSON file, edit the JSON file, and use the Import Data option to bring it back into the system, thus avoiding the perils of DB file editing.  The primary downside of this method would be that it's not very discoverable and would have to be done for each new S&V world that the hypothetical GM sets up. On the other hand, it would be a one-time fix within a given world, so not a bad option.

A more involved method would be to modify the system to set this up as a system setting, which would allow any future GMs to choose for themselves, much like I did with the XP bar sizes.  I only just thought of this while typing all this out, as the two or three people who had previously contacted me to point this discrepancy out all seemed satisfied with my reasoning, so I never prioritized it as an issue.  It's a fairly quick change to make though.

An even more involved method would be adding UI to the Ship Type HTML template to expose those values for modification, which would also allow for a wide variety of homebrew Ship Types.  This is another solution that only came to me as I was typing these out, although I now recall intending to do this at some point during the initial stages of building the system.  This is my preferred solution, as it not only provides an easy way to solve the specific problem you highlighted, but also adds functionality to support other play styles and more creativity, which seems like the better long-term solution.  The downside is that it's not a super quick fix I can throw together in an hour or so, so it will have to wait until I put a little time and effort into it.

You're welcome to contribute your further opinion on these approaches or even suggest additional ones, if you like.  I'm sure this isn't an exhaustive list.  If you need a quicker solution for an imminent game, just let me know if you need additional info beyond what I wrote here.

**Comment by drewg13** [comment]
Well, that was easier than I thought.  I forgot that I switched those values from inherent properties to Active Effects and it was easily end-user editable.  I don't even know what you were so upset about, it was a 10 sec fix.  Anyway, I updated the compendium to have both an E3 Cerberus and an E4 Cerberus, choose whichever you prefer.

**Comment by Ariphaos** [comment]
I apologize for being rash, I was just kind of mystified.

I never looked at the ships in the sheets personally, I just used them as a player aid for those lacking the book. Bad experience with most other systems' character sheets I guess.

**Pull request closed without merging**
