### PR TITLE
Faction sheet tweaks

### PR DESCRIPTION
**Pull request by MarkPearce**
1. Fixed deprecated warnings in en.json for all effected types. eg "TYPES.Actor.faction-status",  "TYPES.Item.planet": "Planet", etc
2. fixed helper function spelling normalizeFactionValue
3. use string comparison for tier helper
4. added faint Neutral labels
5. fix isGM that broke sheet

**I don't think we need a status | Jobs header label.  hover tells you what it is, as does clicking button... I mean it would be better, but theres not really room.  Trying to make sure it fits 1280 screens (foundry min)

### CODE REVIEW

**Comment by drewg13** [comment]
Be careful with the deprecation warnings.  I was leaving those in on purpose until V12 to maintain V10 compatibility.  No idea how many people are still on V10, but I try to maintain at least 2 versions, when it's feasible.

Thanks for the flexibility and the quick response.  I'll mess with it some more tomorrow evening.

**Comment by MarkPearce** [comment]
tested on v10.312 with changes.  no warnings/errors.

[image: image.png]

**Comment by drewg13** [comment]
Oops, didn't mean *that* to happen.

**Comment by drewg13** [comment]
Gotta say, I don't love the opinionated reformatting of unrelated code in `sav.js`.  I'm sure it's something your IDE does and I'm sure the way I do it is dumb, but it's a bit grating on the nerves to have your code arbitrarily rewritten.

I'll revert the V10 deprecation changes you made to `en.json` and the reformatting and it should be good to merge.

**Comment by MarkPearce** [comment]
Sorry it’s automatic on save with prettier.  If you want to share your
config I can resubmit

**Comment by MarkPearce** [comment]
The v10 changes are fines, tested it on 10.312

**Comment by drewg13** [comment]
No, I took care of it all, no worries.  I saw you made the V10 comment, but didn't realize what it was referring to.  My testing shows the same, good to know.  I'll revert that then.

**Comment by drewg13** [comment]
Nope, my mistake, I hadn't reverted before testing, that change will have to wait until my first V12 release.  It doesn't *break* anything in terms of actual errors, but it no longer translates the entries in the Create New Item or Create New Actor type dropdowns.  It's not a huge issue for English speakers, as you just get the type keys in lowercase with underscores, but I do have foreign users for whom it would break their translations in V10.

image

**Comment by MarkPearce** [comment]
Oh.... it just uses the type name instead of the actual string value,
tricked me on my test.  Good catch!

I normally leave programming to developers. :p

**Comment by drewg13** [comment]
I get it, I hate deprecation warnings in my console too.  I just have (or had at one point) a significant userbase in Brazil who worked really hard with me to get all of the translation stuff cleaned up and functional.

You're better at programming than I am, I just happen to be a subject matter expert on my own system, having already made these mistakes once or twice (or thrice) before.  I do really appreciate the contribution!  Feel free to fix my f-ed up CSS and/or pretty up the sheets any time you like.

**Comment by MarkPearce** [comment]
localization of strings may not be great for the faction sheet. My CSS is
terrible, so there's fixed width columns in there....

Is there a portuguese language file i could test with?

Why don't I add in text-overflow: ellipsis To prevent overlapping?

**Comment by drewg13** [comment]
There are modules for Portuguese and Spanish that add in Babele support for translation of the compendium content as well.  You can find the links in the README.  They're both probably out of date though.

**Pull request merged**
